source("Simulation_Function.R")

n.repeat = 100
# a. change sample size of the first area
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
for (n1 in c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500)){
  # result = Evaluation(p=8, n1=n1, n2=500, variance=1, rho=0.8, n.k=n.repeat)
  result = Evaluation.K(p=8, n=c(n1,500), variance=1, rho=0.8, n.k=n.repeat)
  print(proc.time() - ptm)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)
A = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "a1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,2], type = "n", xlab = "Sample Size of the 1st Area", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500),cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
#lines(result.mean[,6], lwd=2, col="black", lty="solid")
#lines(result.05[,6], lwd=2, col="black", lty="dotted")
#lines(result.95[,6], lwd=2, col="black", lty="dotted")
#legend("topright", legend = c("Correlation Model", "Independent Model", "Importance Sampling"), lwd=c(2,2,2), lty = c("solid", "dotted", "dotted"), col=c("black", "red", "blue"))
dev.off()
pdf(file=paste("PlotSimulation/", "a2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Sample Size of the 1st Area", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500),cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

# b. change sample size of the second area
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
for (n2 in c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500)){
  #result = Evaluation(p=8, n1=5, n2=n2, variance=1, rho=0.8, n.k=n.repeat)
  result = Evaluation.K(p=8, n=c(5,n2), variance=1, rho=0.8, n.k=n.repeat)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)
B = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "b1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,5], type = "n", xlab = "Sample Size of the 2nd Area", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500),cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
dev.off()
pdf(file=paste("PlotSimulation/", "b2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Sample Size of the 2nd Area", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(5, 10, 25, 50, 75, 100, 200, 300, 400, 500),cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

# c. change correlation
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
for (rho in seq(0,0.9,0.1)){
  result = Evaluation(p=8, n1=5, n2=500, variance=1, rho=rho, n.k=n.repeat)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)
C = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "c1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,5], type = "n", xlab = "Prior Correlation", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=seq(0,0.9,0.1),cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
dev.off()
pdf(file=paste("PlotSimulation/", "c2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Prior Correlation", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=seq(0,0.9,0.1),cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

# d. change prior variance
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
for (variance in (1/c(1,2,5,10,20,50,100))){
  result = Evaluation(p=8, n1=5, n2=500, variance=variance, rho=0.8, n.k=n.repeat)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)
D = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "d1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,5], type = "n", xlab = "Prior Effective Sample Size", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(1,2,5,10,20,50,100),cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
dev.off()
pdf(file=paste("PlotSimulation/", "d2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Prior Effective Sample Size", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(1,2,5,10,20,50,100),cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

# e. change dimension p
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
for (p in c(1,2,5,10,15,20)){
  result = Evaluation(p=p, n1=5, n2=500, variance=1, rho=0.8, n.k=n.repeat)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)
E = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "e1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,5], type = "n", xlab = "Dimension", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(1,2,5,10,15,20), cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
dev.off()
pdf(file=paste("PlotSimulation/", "e2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Dimension", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=c(1,2,5,10,15,20), cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

# f. change number of areas K
result.mean = result.05 = result.95 = NULL
ptm <- proc.time()
n = 5
for (i in 1:9){
  n = c(n, 500)
  result = Evaluation.K(p=8, n=n, variance=1, rho=0.8, n.k=n.repeat)
  print(n)
  result = cbind(result, result[,2] - result[,1], result[,2] - result[,3], result[,3] - result[,1])
  result.mean = rbind(result.mean, apply(result,2,mean))
  result.05 = rbind(result.05, apply(result,2,quantile,0.05))
  result.95 = rbind(result.95, apply(result,2,quantile,0.95))
}
print(proc.time() - ptm)

F = list(result.mean,result.05,result.95)
pdf(file=paste("PlotSimulation/", "f1.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,5], type = "n", xlab = "Number of Areas", ylab = "MAE Reduction", ylim = c(min(result.05[,5]),max(result.95[,5])), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=2:10,cex.axis=1.5)
lines(result.mean[,5], lwd=2, col="black", lty="solid")
lines(result.05[,5], lwd=2, col="black", lty="dotted")
lines(result.95[,5], lwd=2, col="black", lty="dotted")
abline(h=0, lty=2, lwd=1, col="red")
lines(result.mean[,6], lwd=2, col="blue", lty="solid")
lines(result.05[,6], lwd=2, col="blue", lty="dotted")
lines(result.95[,6], lwd=2, col="blue", lty="dotted")
dev.off()
pdf(file=paste("PlotSimulation/", "f2.pdf", sep=""), width = 6, height = 4.5)
par(mar = c(4.5, 4.5, 1, 0.5))
plot(result.mean[,4], type = "n", xlab = "Number of Areas", ylab = "Unique Samples", ylim = c(0,1000), cex.lab=1.8, cex.axis=1.5, xaxt="n")
axis(side=1, at=1:nrow(result.mean), labels=2:10, cex.axis=1.5)
lines(result.mean[,4], lwd=2, col="black", lty="solid")
lines(result.05[,4], lwd=2, col="black", lty="dotted")
lines(result.95[,4], lwd=2, col="black", lty="dotted")
dev.off()

